sudo: true

language: php
php:
 - 7.0
 
notifications: 
 email: false

before_script:
 - git submodule sync
    - git submodule update --init
    - rm -rf plugins
    - rm -rf bin
    - rm -rf artifacts
    - mkdir plugins
    - mkdir artifacts
    - wget -O PHP7.tar.gz https://dl.bintray.com/pocketmine/PocketMine/PHP_7.0.6_x86-64_Linux.tar.gz --no-check-certificate
    - tar -xf PHP7.tar.gz
    - wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar

script:
 - bin/php7/bin/php ci.php
